version: '3'

services:
  postgres:
    image: 'postgres:11'
    container_name: 'postgres-db'
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '54320:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
